name 'apache'
maintainer 'Emanuel'
maintainer_email 'emanuelburgess@gmail.com'
license 'all_rights'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '0.2.1'
